# Use singular theme
theme = "singular"

# Site Base Information
baseURL = "https://gohugo.io/"
title = "Ежедневния циник"
copyright = "Copyright License by Ежедневния циник"

# Language
languageCode = "bg"
DefaultContentLanguage = "bg"

# Markup
paginate = 3
enableInlineShortcodes = true
pygmentsCodefences = true

# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]

[params]
  description = "Блогът на циника"
  [params.logo]
    url = "/images/icon.jpg"

[markup]
  [markup.highlight]
    codeFences = true
    noClasses = true
    style = "github"

[permalinks]
	post = "/:year/:month/:day/:filename/"
	page = "/:filename/"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[privacy]
  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]
  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true
